# Generated by Django 6.0.2 on 2026-03-12 16:35

import api.models.pet
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedDocument',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=24)),
                ('file_name', models.CharField(max_length=200)),
                ('file_uri', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(help_text='Ex: vaccination, vet visit, grooming', max_length=100)),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('provider', models.CharField(blank=True, help_text='Name of the personthat provided the service', max_length=200)),
                ('clinic', models.CharField(blank=True, help_text='Name of the clinic where the event took place', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details about the event')),
                ('follow_up_date', models.DateField(blank=True, help_text='Date for any follow-up actions or appointments related to this event', null=True)),
                ('attached_documents', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=api.models.pet.AttachedDocument), blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=24)),
                ('type', models.CharField(help_text='Ex: vaccination reminder, vet appointment', max_length=100)),
                ('header', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date_sent', models.DateTimeField()),
                ('date_clicked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('schema', models.CharField(default='1.0', help_text='Version of the document schema', max_length=10)),
                ('user_ids', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, help_text='Users list that have this pet')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(help_text='Ex: dog, cat, rabbit', max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, help_text='Ex: healthy, needs attention, etc.', max_length=20)),
                ('is_NfC_syched', models.BooleanField(default=False, help_text='Indicates if the pet is synced with NFC tag')),
                ('known_allergies', models.TextField(blank=True, help_text='Known allergies or sensitivities')),
                ('default_vet', models.CharField(blank=True, help_text='Name of the default veterinarian', max_length=200)),
                ('default_clinic', models.CharField(blank=True, help_text='Name of the default clinic', max_length=200)),
                ('vaccinations', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=api.models.pet.Vaccination), blank=True, default=list)),
                ('events', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=api.models.pet.Event), blank=True, default=list)),
                ('notifications', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=api.models.pet.Notification), blank=True, default=list)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('pet_ids', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, help_text='Id of the pets that belong to this user')),
                ('name', models.CharField(max_length=150)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.CharField(max_length=24)),
                ('date_given', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, help_text='Ex: completed, pending, overdue', max_length=20)),
                ('administered_by', models.CharField(blank=True, help_text='Name of the person or clinic that administered the vaccine', max_length=200)),
                ('attached_documents', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=api.models.pet.AttachedDocument), blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('characteristics', models.TextField(blank=True)),
                ('application_moment', models.CharField(blank=True, help_text='Ex: 8 weeks, annual, every 3 years', max_length=200)),
                ('animal_type', models.CharField(help_text='Ex: dog, cat, rabbit', max_length=100)),
            ],
            options={
                'db_table': 'vaccines',
            },
        ),
    ]
