# Generated by Django 6.0.2 on 2026-02-17 22:02

import api.models
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('file_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinationEvent',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('booster_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('user_ids', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, help_text='Users list that have this pet')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(help_text='Ex: dog, cat, rabbit', max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('behavior_notes', models.TextField(blank=True, help_text='Behavior, special care, etc.')),
                ('vaccination_events', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=api.models.VaccinationEvent), blank=True, default=list)),
                ('medical_history', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=api.models.MedicalRecord), blank=True, default=list)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('pet_ids', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, help_text='Id of the pets that belong to this user')),
                ('name', models.CharField(max_length=150)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('characteristics', models.TextField(blank=True)),
                ('application_moment', models.CharField(blank=True, help_text='Ex: 8 weeks, annual, every 3 years', max_length=200)),
                ('animal_type', models.CharField(help_text='Ex: dog, cat, rabbit', max_length=100)),
            ],
            options={
                'db_table': 'vaccines',
            },
        ),
    ]
