# Generated by Django 6.0.2 on 2026-03-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='is_NfC_syched',
            new_name='is_nfc_synced',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='application_moment',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='intervalDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='productName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='schema',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='species',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
