# Generated by Django 6.0.2 on 2026-03-13 01:59

import django.core.validators
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_is_nfc_syched_pet_is_nfc_synced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="user@email.com", max_length=300),
        ),
        migrations.AddField(
            model_name="user",
            name="family_group",
            field=django_mongodb_backend.fields.ArrayField(
                base_field=django_mongodb_backend.fields.ObjectIdField(),
                blank=True,
                default=list,
                help_text="Id of the users in the family group",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="initials",
            field=models.CharField(
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Initials must be on Uppercase (max. 5)",
                        regex="^[A-ZÁÉÍÓÚÑ]{1,5}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pet_ids",
            field=django_mongodb_backend.fields.ArrayField(
                base_field=django_mongodb_backend.fields.ObjectIdField(),
                blank=True,
                default=list,
                help_text="Id of the pets that belong to this user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid phone number",
                        regex="^\\+?[0-9\\s\\-\\(\\)]{7,20}$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["firebase_uid"], name="idx_user_firebase_uid"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="idx_user_email"),
        ),
    ]
